---

# DEPENDENCIES INSTALLATION
- name: "[Nextcloud - linux] Installation of dependencies"
  apt: 
    pkg: {{ deps }}
  become: True

# POSTGRESQL INSTALL - ADD REPOS TOO - DON'T TOUCH IT WORKS
- name: add postgres repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add postgresql to sources list
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    validate_certs: true
    update_cache: true
    state: present

- name: apt install postgresql-client with Update
  apt:
    name: 
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-client-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
      - "postgresql-server-dev-{{ postgresql_version }}"
    state: latest
    update_cache: true
    
- name: install psycopg2
  pip: 
    name: 
      - psycopg2-binary
      - pip
    state: latest
  become: true

- name: ensure postgres is running
  systemd:
    name:    postgresql
    enabled: true
    state:   started

# REDIS INSTALLATION
- name: "[Nextcloud - linux] Installation of Redis"
  apt:
    name: redis
    state: latest
  become: True 

# TARBALL DOWNLOAD & DEPLOY
- name: "[Nextcloud - linux] Tarball download"
  get_url:
    url: https://download.nextcloud.com/server/releases/nextcloud-21.0.0.tar.bz2
    dest: /opt/
  become: True

- name: 