---

- name: "[zabbix_agent2 - linux] Installation of the repo"
  apt: 
    deb: https://repo.zabbix.com/zabbix/5.2/debian/pool/main/z/zabbix-release/zabbix-release_5.2-1+debian10_all.deb
    update_cache: Yes
  become: True
    
- name: "[zabbix_agent2 - linux] Installation agent zabbix v2"
  apt: 
    name: zabbix-agent2
    state: present
    update_cache: Yes
  become: True

#- name: "[zabbix_agent2 - linux] Configuration de l'agent zabbix"
#  template:
#    src: "zabbix_agent2.conf.j2"
#    dest: "/etc/zabbix/zabbix_agent2.conf"
#    mode: 0644
#  become: True

- name: "[zabbix_agent - linux] Demarrage de l'agent"
  service: 
    name: zabbix-agent2 
    state: restarted
    enabled: Yes
  become: True